apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
  namespace: budget
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget
  template:
    metadata:
      labels:
        app: budget
    spec:
      containers:
      - name: budget
        image: nishank840/budget-app:latest
        ports:
        - containerPort: 80
