apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nishank841/argocd-demo.git
    targetRevision: HEAD
    path: budget-app
  destination:
    server: https://kubernetes.default.svc
    namespace: budget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
